//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFee
    {
        public int Id { get; set; }
        public Nullable<int> FeeType_Id { get; set; }
        public int Client_Id { get; set; }
        public int Scheme_Id { get; set; }
        public decimal FeeExclVAT { get; set; }
    
        public virtual FeeType FeeType { get; set; }
        public virtual Client Client { get; set; }
    }
}
