//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientNote
    {
        public ClientNote()
        {
            this.ClientNoteTags = new HashSet<ClientNoteTag>();
        }
    
        public int Id { get; set; }
        public int Client_Id { get; set; }
        public Nullable<int> ClientNoteCategory_Id { get; set; }
        public string NoteTitle { get; set; }
        public string NoteContent { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool Obsolete { get; set; }
    
        public virtual ClientNoteCategory ClientNoteCategory { get; set; }
        public virtual ICollection<ClientNoteTag> ClientNoteTags { get; set; }
        public virtual Client Client { get; set; }
    }
}
