//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public int Client_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ContractType_Id { get; set; }
        public int BillingAddress_Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> Recurs { get; set; }
        public Nullable<int> RecurrenceFrequency { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<decimal> ContractValue { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> DailyRate { get; set; }
        public Nullable<int> RenewalID { get; set; }
        public Nullable<bool> Autobill { get; set; }
        public Nullable<System.DateTime> Origstartdate { get; set; }
        public Nullable<int> AutoBillFrequency { get; set; }
        public Nullable<System.DateTime> NextAutoBill { get; set; }
        public string ContractHistory { get; set; }
        public Nullable<bool> DefaultContract { get; set; }
        public Nullable<bool> DirectDebit { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
