//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Permission_Mapping
    {
        public int Id { get; set; }
        public int Contact_Id { get; set; }
        public int Scheme_Id { get; set; }
        public int Permission_Id { get; set; }
    
        public virtual DdScheme DdScheme { get; set; }
        public virtual Permission Permission { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
