//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DdInstructionNote
    {
        public int Id { get; set; }
        public int DdInstruction_Id { get; set; }
        public Nullable<int> DdInstructionNoteCategory_Id { get; set; }
        public string NoteContent { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual DdInstruction DdInstruction { get; set; }
        public virtual DdInstructionNoteCategory DdInstructionNoteCategory { get; set; }
    }
}
