//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DdInstructionAttributeValue
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int DdInstruction_Id { get; set; }
        public int DdInstructionAttribute_Id { get; set; }
    
        public virtual DdInstruction DdInstruction { get; set; }
        public virtual DdInstructionAttribute DdInstructionAttribute { get; set; }
    }
}
