//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DdInstructionAttribute
    {
        public DdInstructionAttribute()
        {
            this.DdInstructionAttributeValues = new HashSet<DdInstructionAttributeValue>();
            this.DdSchemes = new HashSet<DdScheme>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsRequired { get; set; }
        public int AttributeControlType_Id { get; set; }
        public int DisplayOrder { get; set; }
        public bool AdminOnly { get; set; }
        public string AttributeOptions { get; set; }
        public bool AllSchemes { get; set; }
    
        public virtual ICollection<DdInstructionAttributeValue> DdInstructionAttributeValues { get; set; }
        public virtual ICollection<DdScheme> DdSchemes { get; set; }
    }
}
