//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DdInstruction
    {
        public DdInstruction()
        {
            this.DdInstructionAttributeValues = new HashSet<DdInstructionAttributeValue>();
            this.DdInstructionNotes = new HashSet<DdInstructionNote>();
        }
    
        public int Id { get; set; }
        public int Scheme_Id { get; set; }
        public string DdReference { get; set; }
        public bool DdiActive { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string SortCode { get; set; }
        public int ScheduleType_Id { get; set; }
        public Nullable<decimal> FirstPaymentAmount { get; set; }
        public Nullable<System.DateTime> FirstPaymentDate { get; set; }
        public Nullable<decimal> ScheduledPaymentAmount { get; set; }
        public Nullable<System.DateTime> ScheduledPaymentDate { get; set; }
        public Nullable<int> ScheduledPaymentCount { get; set; }
        public Nullable<decimal> LastPaymentAmount { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> FrequencyInterval { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public bool NewInstructionRequired { get; set; }
        public Nullable<System.DateTime> NewInstructionInPlace { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelNote { get; set; }
        public string CancelCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string FileAuditID { get; set; }
        public string SignUpType { get; set; }
        public string AmendCode { get; set; }
        public int UnpaidSeqCount { get; set; }
        public Nullable<System.DateTime> AmendedOn { get; set; }
        public Nullable<int> AmendReportFlag { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> DdiTagID { get; set; }
        public byte[] DdiTimestamp { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> ContactAddress_Id { get; set; }
        public Nullable<int> AlternateAddress_Id { get; set; }
    
        public virtual DdScheme DdScheme { get; set; }
        public virtual ICollection<DdInstructionAttributeValue> DdInstructionAttributeValues { get; set; }
        public virtual ICollection<DdInstructionNote> DdInstructionNotes { get; set; }
    }
}
