//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DdScheme
    {
        public DdScheme()
        {
            this.Contact_Permission_Mapping = new HashSet<Contact_Permission_Mapping>();
            this.DdInstructions = new HashSet<DdInstruction>();
            this.DdInstructionAttributes = new HashSet<DdInstructionAttribute>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SUN { get; set; }
        public int Client_Id { get; set; }
        public Nullable<int> ManagedByClient_Id { get; set; }
        public Nullable<int> BillingAddress_Id { get; set; }
        public int SchemeType_Id { get; set; }
        public string SchemeCode { get; set; }
        public string RemittersName { get; set; }
        public string AccountName { get; set; }
        public string SortCode { get; set; }
        public string AccountNumber { get; set; }
        public bool WebOnly { get; set; }
        public Nullable<int> WebScheme_Id { get; set; }
        public bool SendBacsNewInstruction { get; set; }
        public int NewInstructionNoticeInDays { get; set; }
        public bool SendBacsCancellation { get; set; }
        public Nullable<int> BacsCancellationWaitInDays { get; set; }
        public bool DdRefMustBeUnique { get; set; }
        public Nullable<System.DateTime> ScheduleLastExtended { get; set; }
        public bool Represent { get; set; }
        public Nullable<int> RepresentOffset { get; set; }
        public string RepresentSchedule { get; set; }
        public bool SchemeLocked { get; set; }
        public System.DateTime SchemeLockedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool HasLetterGeneration { get; set; }
        public bool CommunicateByFTP { get; set; }
        public bool RestrictPaymentDates { get; set; }
        public string AllowedPaymentDates { get; set; }
        public int KeepFTPHistoryInMonths { get; set; }
        public string ProductConfig { get; set; }
    
        public virtual ICollection<Contact_Permission_Mapping> Contact_Permission_Mapping { get; set; }
        public virtual ICollection<DdInstruction> DdInstructions { get; set; }
        public virtual DdSchemeType DdSchemeType { get; set; }
        public virtual ICollection<DdInstructionAttribute> DdInstructionAttributes { get; set; }
        public virtual Client Client { get; set; }
    }
}
