//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileType
    {
        public FileType()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int FileTypeId { get; set; }
        public string FileType1 { get; set; }
        public string FileTypeNote { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
