//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrinityEntities : DbContext
    {
        public TrinityEntities()
            : base("name=TrinityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientAttribute> ClientAttributes { get; set; }
        public virtual DbSet<ClientAttributeValue> ClientAttributeValues { get; set; }
        public virtual DbSet<ClientCategory> ClientCategories { get; set; }
        public virtual DbSet<ClientFee> ClientFees { get; set; }
        public virtual DbSet<ClientNoteCategory> ClientNoteCategories { get; set; }
        public virtual DbSet<ClientNoteTag> ClientNoteTags { get; set; }
        public virtual DbSet<Contact_Permission_Mapping> Contact_Permission_Mapping { get; set; }
        public virtual DbSet<ContactCategory> ContactCategories { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DdInstruction> DdInstructions { get; set; }
        public virtual DbSet<DdInstructionAttribute> DdInstructionAttributes { get; set; }
        public virtual DbSet<DdInstructionAttributeValue> DdInstructionAttributeValues { get; set; }
        public virtual DbSet<DdInstructionNote> DdInstructionNotes { get; set; }
        public virtual DbSet<DdInstructionNoteCategory> DdInstructionNoteCategories { get; set; }
        public virtual DbSet<DdNewSignUpControl> DdNewSignUpControls { get; set; }
        public virtual DbSet<DdScheme> DdSchemes { get; set; }
        public virtual DbSet<DdSchemeType> DdSchemeTypes { get; set; }
        public virtual DbSet<FeeType> FeeTypes { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PermissionGrp> PermissionGrps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ApplicationSetting> ApplicationSettings { get; set; }
        public virtual DbSet<ClientNote> ClientNotes { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Client_Address_Mapping> Client_Address_Mapping { get; set; }
    }
}
