//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.Contact_Permission_Mapping = new HashSet<Contact_Permission_Mapping>();
            this.PermissionGrps = new HashSet<PermissionGrp>();
        }
    
        public int Id { get; set; }
        public string Permission1 { get; set; }
    
        public virtual ICollection<Contact_Permission_Mapping> Contact_Permission_Mapping { get; set; }
        public virtual ICollection<PermissionGrp> PermissionGrps { get; set; }
    }
}
